# Generated by Django 2.0.1 on 2018-02-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapps', '0003_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
